---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/31 17:08
---

BagUI={}
local this=BagUI
BagUI.uiName = "Layout_1/Canvas_Bag"
function BagUI.Init(root)
    this.root = root
    BagUI.articlesParent=this.root.transform:Find("articles")
end


function BagUI.OnShow()
    this.root:SetActive(true)
end
function BagUI.OnHide()
    this.root:SetActive(false)
end