---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/31 17:08
---

BagUI=UIBase:new()
local this=BagUI
BagUI.uiName = "Layout_1/Canvas_Bag"
function BagUI.Init(root)
    this.root = root
    BagUI.articlesParent=this.root.transform:Find("articles")
end


