---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/27 16:02
---
OperatorUI = {}
this=OperatorUI
OperatorUI.uiName = "Canvas_Operator"

function OperatorUI.Init(root)
    this.root = root
end
function OperatorUI.OnShow()
    this.root:SetActive(true)
end
function OperatorUI.OnHide()
    this.root:SetActive(false)
end