---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/27 16:02
---
SquadsUI = {}
this=SquadsUI
SquadsUI.uiName = "Canvas_Squads"
function SquadsUI.Init(root)

    this.root = root
end
function SquadsUI.OnShow()
    this.root:SetActive(true)
end
function SquadsUI.OnHide()
    this.root:SetActive(false)
end