---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/26 21:32
---

UI=CS.UnityEngine.UI
StoreUI = UIBase:new()

function StoreUI:new()
    local o = {UIBase:new()}
    setmetatable(o,{__index = self})
    return o
end


local this = StoreUI
this.uiName = "Layout_1/Canvas_Store"
this.uiStoreDic = {}
this.uiStoreRoot = nil

function StoreUI.Init(root)
    this.root = root

    this.uiStoreDic["CreditStoreUI"] = CreditStoreUI
    this.uiStoreDic["VoucherStoreUI"] = VoucherStoreUI

    this.button_Back = this.root.transform:Find("Button_Back"):GetComponent("Button")
    --this.button_Back.onClick.AddListener(StoreUI.OnButtonClick_Back)
    CS.UIUtil.SetButtonEventLua(this.button_Back, this.OnButtonClick_Back)

    --StoreUI.OnHide()
    StoreUI.SetUIRoot()
end

function StoreUI.SetUIRoot()
    for key, view in pairs(this.uiStoreDic) do
        local root = this.root.transform:Find(view.uiName).gameObject
        view.Init(root)
    end
end
function StoreUI.OnButtonClick_Back()
    UISystem.OpenView(UIEnum.MainUI)
    UISystem.CloseView(UIEnum.StoreUI)
end

function StoreUI.StoreUIRoot()
    for key, view in pairs(this.uiStoreDic) do
        local root = this.root.transform:Find(view.uiName).gameObject
        view.Init(root)
    end
end

