---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/26 21:32
---

UI=CS.UnityEngine.UI
StoreUI = UIBase:new()

StoreUI.items = {}

function StoreUI:new()
    local o = {UIBase:new()}
    setmetatable(o,{__index = self})
    return o
end


local this = StoreUI
this.uiName = "Layout_1/Canvas_Store"


function StoreUI.Init(root)
    this.root = root

    this.button_Back = this.root.transform:Find("Button_Back"):GetComponent("Button")
    --this.button_Back.onClick.AddListener(StoreUI.OnButtonClick_Back)
    CS.UIUtil.SetButtonEventLua(this.button_Back, this.OnButtonClick_Back)

    ---初始化打开商店的第一个界面
    StoreUI.currentView = this.root.transform:Find("Store/Buttons/Button_Recommend/Voucher").gameObject
    --StoreUI.OnHide()
end

function StoreUI.OnButtonClick_Back()
    UISystem.OpenView(UIEnum.MainUI)
    UISystem.CloseView(UIEnum.StoreUI)
    StoreUI.ClearItems()
    CreditStoreUI.ifCommodityPrefab = true
    VoucherStoreUI.ResetIfCommodityPrefabDic()
    print(VoucherStoreUI.ifCommodityPrefabDic["Credential"])
    ClothingStoreUI.ifCommodityPrefab = true
end

---关闭之前的view记录当前要打开的view并打开
function StoreUI.RecordViewButton(gobj)
    StoreUI.currentView:SetActive(false)
    StoreUI.currentView = gobj
    StoreUI.currentView:SetActive(true)
end

function StoreUI.ClearItems()
    for key, view in pairs(StoreUI.items) do
        CS.UnityEngine.GameObject.Destroy(view)
    end
end
