---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/26 21:32
---
StoreUI = {}
local this = StoreUI
this.uiName = "Canvas_Store"

function StoreUI.Init(root)
    this.root = root


end

function StoreUI.OnShow(root)
    this.root:SetActive(true)

end

function StoreUI.OnButton1Click()
    UISystem.OpenView(UIEnum.MainUI)
end

function StoreUI.OnHide(root)
    this.root:SetActive(false)

end

