---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/31 19:05
---

TerminalUI={}
local this=TerminalUI

TerminalUI.uiName = "Layout_1/Canvas_Terminal"
TerminalUI.UnlockedLevels = 0
TerminalUI.Levels = {}

function TerminalUI.Init(root)
    this.root = root
    local content = this.root.transform:Find("Scroll View/Viewport/Content")
    for i = 1, content.childCount, 1 do
        local child = content:GetChild(i-1)

        local data = {
            id = i,
            go = child,
        }

        this.Levels[i] = data
        local button = child:GetComponent("Button")
        CS.UIUtil.SetButtonEventLua(button, function() this.OnButtonClick_Levels(data) end)
    end
    this.UnLockLevel(1)
    this.button_Back = this.root.transform:Find("Button_Back"):GetComponent("Button")
    CS.UIUtil.SetButtonEventLua(this.button_Back, this.OnButtonClick_Back)
end

function TerminalUI.OnButtonClick_Levels(data)
    this.UnLockLevel(data.id + 1)
end

function TerminalUI.UnLockLevel(number)
    if this.Levels[number] ~= nil then
        this.Levels[number].go.gameObject:SetActive(true);
    end
end

function TerminalUI.OnButtonClick_Back()
    UISystem.OpenView(UIEnum.MainUI)
    UISystem.CloseView(UIEnum.TerminalUI)
end



function TerminalUI.OnShow()
    this.root:SetActive(true)
end

function TerminalUI.OnHide()
    this.root:SetActive(false)
end