---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/11/2 16:13
---
UIBase = {}
function UIBase:new()
    local o = {}
    setmetatable(o,{__index = self})
    return o
end



function UIBase.OnShow(uiEnum)
    UISystem.uiDic[uiEnum].root:SetActive(true)

end

function UIBase.OnHide(uiEnum)
    UISystem.uiDic[uiEnum].root:SetActive(false)

end
