---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/26 21:35
---
UIEnum = {}
UIEnum.StoreUI = "StoreUI"
UIEnum.MainUI = "MainUI"
UIEnum.OperatorUI = "OperatorUI"
UIEnum.SquadsUI = "SquadsUI"
