---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/26 21:23
---
require("View/UIBase")

require("View/MainUI")
require("View/StoreUI")
require("View/OperatorUI")
require("View/SquadsUI")
require("View/BagUI")
require("View/TerminalUI")

require("View/SubViews/CreditStoreUI")
require("View/SubViews/VoucherStoreUI")
require("View/SubViews/ClothingStoreUI")
require("View/SubViews/SourceStoneStoreUI")

require("Item/ItemVoucher")
require("Item/ItemCommoditySourceStone")


UISystem = {}
local this = UISystem

this.uiDic = {}
this.uiRoot = nil

function UISystem.Init()
    print("UISystem.Init() ")
    this.uiDic[UIEnum.StoreUI] = StoreUI
    this.uiDic[UIEnum.MainUI] = MainUI
    this.uiDic[UIEnum.OperatorUI] = OperatorUI
    this.uiDic[UIEnum.SquadsUI] = SquadsUI
    this.uiDic[UIEnum.BagUI] = BagUI
    this.uiDic[UIEnum.TerminalUI] = TerminalUI

    this.uiDic[UIEnum.CreditStoreUI] = CreditStoreUI
    this.uiDic[UIEnum.VoucherStoreUI] = VoucherStoreUI
    this.uiDic[UIEnum.ClothingStoreUI] = ClothingStoreUI
    --this.uiDic[UIEnum.SourceStoneStoreUI] = SourceStoneStoreUI

    this.uiRoot = CS.UnityEngine.GameObject.Find("UIRoot")
    this.SetUIRoot()
    this.OpenView(UIEnum.MainUI)

end

function UISystem.SetUIRoot()
    for key, view in pairs(this.uiDic) do
        local root = this.uiRoot.transform:Find(view.uiName).gameObject
        view.Init(root)
    end
end

function UISystem.OpenView(uiEnum)
    this.uiDic[uiEnum].OnShow(uiEnum)

end

function UISystem.CloseView(uiEnum)
    this.uiDic[uiEnum].OnHide(uiEnum)

end