---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/26 21:23
---
require("View/MainUI")
require("View/StoreUI")

UISystem = {}
local this = UISystem

this.uiDic = {}
this.uiRoot = nil

function UISystem.Init()
    this.uiDic[UIEnum.StoreUI] = StoreUI
    this.uiDic[UIEnum.MainUI] = MainUI

    this.uiRoot = CS.UnityEngine.Gameobject.Find("UIRoot")
    this.SetUIRoot()
end

function UISystem.SetUIRoot()
    for key, view in pairs(this.uiDic) do
        local root = CS.UnityEngine.Gameobject.Find(view.uiName)
        view.Init(root)
    end
end

function UISystem.OpenView(uiEnum)
    this.uiDic[uiEnum].OnShow()

end

function UISystem.CloseView(uiEnum)

end