---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/11/15 14:03
---
ClothingStoreUI=StoreUI:new()
local this = ClothingStoreUI
this.uiName = "Layout_1/Canvas_Store/Store/Buttons/Button_FashionHouse"


function ClothingStoreUI.Init(root)
    this.root = root
    this.ifCommodityPrefab = true
    this.button_FashionHouse = this.root:GetComponent("Button")

    print(this.button_FashionHouse)
    CS.UIUtil.SetButtonEventLua(this.button_FashionHouse, this.OnButtonClick_FashionHouse)
    this.content = this.root.transform:Find("Content").gameObject
    this.commodities = this.root.transform:Find("Content/ScrollView/Viewport/Commodity")
    this.couturePrefab = CS.UIUtil.GetPrefabLua("Prefabs/Couture")


end
function ClothingStoreUI.OnButtonClick_FashionHouse()

    StoreUI.RecordViewButton(this.content)

    if this.ifCommodityPrefab then
        this.ifCommodityPrefab = false
        for i = 1, 20, 1 do
            local go = CS.UnityEngine.GameObject.Instantiate(this.couturePrefab, this.commodities.transform)
            table.insert(StoreUI.items,go)
            local button = go.transform:Find("Button_Couture"):GetComponent("Button")
            local img = go.transform:Find("Image_Held").gameObject


            CS.UIUtil.SetButtonEventLua(button, function() this.OnButtonClick_Commodities(img) end)
        end
    end

end
function ClothingStoreUI.OnButtonClick_Commodities(img)
    img:SetActive(true)
    CS.UnityEngine.GameObject.Instantiate(this.couturePrefab, BagUI.articlesParent)
end