---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/28 19:40
---
CreditStoreUI={}
local this = CreditStoreUI
this.uiName = "Store/Buttons/Button_credit"


function CreditStoreUI.Init(root)
    this.root = root
    this.ifCommodityPrefab = true
    this.button_credit = this.root:GetComponent("Button")
    CS.UIUtil.SetButtonEventLua(this.button_credit, this.OnButtonClick_Credit)
    this.commodities = this.root.transform:Find("commodities")
    this.commodityPrefab = CS.UIUtil.GetPrefabLua("Prefabs/commodity")

    --this.commodityPrefabButton = this.commodityPrefab.transform:Find("Button_commodity"):GetComponent("Button")
    --CS.UIUtil.SetButtonEventLua(this.commodityPrefabButton,this.OnButtonClick_Commodities)

end





function CreditStoreUI.OnButtonClick_Credit()

    if this.ifCommodityPrefab then
        this.ifCommodityPrefab = false
        for i = 1, 10, 1 do
            local go = CS.UnityEngine.GameObject.Instantiate(this.commodityPrefab, this.commodities.transform)
            local button = go.transform:Find("Button_commodity"):GetComponent("Button")
            CS.UIUtil.SetButtonEventLua(button, function() this.OnButtonClick_Commodities(go) end)
        end
    end


end
function CreditStoreUI.OnButtonClick_Commodities(go)
    go:SetActive(false)
end



function CreditStoreUI.OnShow()
    this.root:SetActive(true)
    this.ifCommodityPrefab = true
end
function CreditStoreUI.OnHide()
    this.root:SetActive(false)

end