---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/28 19:40
---
creditStoreUI={}
local this = creditStoreUI
this.uiName = "Store/Buttons/Button_credit"
function creditStoreUI.Init(root)
    this.root = root
    this.button_credit = this.root:GetComponent("Button")
    CS.UIUtil.SetButtonEventLua(this.button_credit, this.OnButtonClick_Credit)
    this.commodities = this.root.transform:Find("Store/Buttons/Button_credit/commodities")

end

function creditStoreUI.OnButtonClick_Credit()

    CS.UnityEngine.GameObject.Instantiate()
end




function creditStoreUI.OnShow()
    this.root:SetActive(true)

end
function creditStoreUI.OnHide()
    this.root:SetActive(false)

end