---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/11/15 17:58
---
SourceStoneStoreUI=StoreUI:new()
local this = SourceStoneStoreUI
this.uiName = "Layout_1/Canvas_Store/Store/Buttons/Button_SourceStone"


function SourceStoneStoreUI.Init(root)
    this.root = root
    this.ifCommodityPrefab = true
    this.button_SourceStone = this.root:GetComponent("Button")

    print(this.button_SourceStone)
    CS.UIUtil.SetButtonEventLua(this.button_SourceStone, this.OnButtonClick_SourceStone)
    this.content = this.root.transform:Find("Content").gameObject
    this.commodities = this.root.transform:Find("Content/ScrollView/Viewport/Commodity")
    this.commoditySourceStonePrefab = CS.UIUtil.GetPrefabLua("Prefabs/Commodity_SourceStone")


end
function SourceStoneStoreUI.OnButtonClick_SourceStone()

    ItemCommoditySourceStone.Init()
    StoreUI.RecordViewButton(this.content)

    if this.ifCommodityPrefab then
        this.ifCommodityPrefab = false
        for i = 1, 6, 1 do
            local go = CS.UnityEngine.GameObject.Instantiate(this.commoditySourceStonePrefab, this.commodities.transform)
            table.insert(StoreUI.items,go)
            local button = go.transform:Find("Button_SourceStone"):GetComponent("Button")
            local img = go.transform:Find("Image_Double").gameObject

            img:SetActive(ItemCommoditySourceStone.ifDouble[i])

            CS.UIUtil.SetButtonEventLua(button, function() this.OnButtonClick_Commodities(img) end)
        end
    end

end


function SourceStoneStoreUI.OnButtonClick_Commodities(img)
    img:SetActive(false)
    CS.UnityEngine.GameObject.Instantiate(this.commoditySourceStonePrefab, BagUI.articlesParent)
end