---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/11/15 18:06
---
ItemCommoditySourceStone = {}
local this = ItemCommoditySourceStone

this.numberList = {1,6,20,40,66,130}
this.priceList = {6,30,98,198,328,648}

function ItemCommoditySourceStone.Init()

    this.ItemDate = CS.UIUtil.GetJsonLua("Json/ItemCommoditySourceStone")
    print(ItemCommoditySourceStone.ItemDate)

    this.number = 1
    this.price = 6
    this.jsonData = JSON.toJSON(this.ItemDate)

    this.ifDouble = this.jsonData.ifDouble
end