---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/11/3 19:58
---
ItemVoucher = {}

ItemVoucher.name = nil
ItemVoucher.Price = nil
ItemVoucher.Discount = nil
ItemVoucher.Remaining = nil

function ItemVoucher.Init()

end